### ISSUE TITLE
Possible problem?

### ISSUE THREAD

**Issue by MiniaczQ** [TerminatorNL/Tiquality#28]
!I did not test this!
To explain the problem I'll use an example:
Say you have a skyblock modded server.
3 players decided to work as a group on one island.
They create a system of blocks together, so that means some blocks belong to one player, while others to another, while they are all online, it works nicely.
From reading your explanation I judge that if only 1 of the players is online the system might not work properly because the "offline player" tick time may be disabled or really low, which would result in part of the system not ticking. That is because I don't see anyone giving "offline players" the same tick time as "online players".
Possible solution:
I suggest adding grouping of players. That way if only 1 player of a group is online he loads all of the blocks of the group.

I hope this somewhat explains the possible problem I'm seeing and gives you some ideas. :)

**Comment by TerminatorNL** [comment]
Multiple owners is not supported at the time. But if you build inside griefprevention or FTB utilities claims all blocks are auto-assigned to the correct player. You can then in turn share your tick wallet to the player that's the owner of the blocks.

This means that all blocks within that claim tick seamlessly, even when the true owner is offline, because it'll take time from the other two players when they are online.
