### ISSUE TITLE
Server hang on import claims

### ISSUE THREAD

**Issue by bigenergy** [TerminatorNL/Tiquality#34]
Run /tq import_griefprevention
Server hang & stopping 
because tpc drops to 1-2

https://hastebin.com/goqutijeqo.php
[debug.log](https://github.com/TerminatorNL/Tiquality/files/3327417/debug.log)

**Comment by TerminatorNL** [comment]
I plan on removing the griefprevention import.
Instead, try to tell players to use /tq claim

Make sure the configuration has a high enough value so they can claim their base easily.

The server TPS drops because Tiquality has to load the chunks in order to properly store data in them. There's no workaround.

**Comment by TerminatorNL** [comment]
I have removed all documentation for GriefPrevention import in [1.12.2-GAMMA-1.5.2](https://github.com/TerminatorNL/Tiquality/releases/tag/1.12.2-GAMMA-1.5.2) (d29d092a83ba98ac01b867d28d82bfc7767f8d24) I keep it in as legacy feature for now, but it will be removed eventually.
