### ISSUE TITLE
Severe Issue - Users Reporting Claim Fails? - 1.12.2 - 1.5.1_1.5.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TerminatorNL/Tiquality#37]
Many users after updating to 1.5.2 have been telling me claiming is not working. Also that they need to keep reclaiming the same area every login.

**Comment by P3rf3ctXZer0** [comment]
![2019-07-03 22_16_45-](https://user-images.githubusercontent.com/10351221/60637664-ec0cae80-9de0-11e9-8e92-1bcfd71c5d01.png)

**Comment by P3rf3ctXZer0** [comment]
Testing 1.12.2 - 1.5.1 from 1.5.2

**Comment by P3rf3ctXZer0** [comment]
I can confirm the issue does not exist in 1.5.1

**Comment by TerminatorNL** [comment]
Can you provide debug.log and latest.log?
It may shed some more light.

**Comment by TerminatorNL** [comment]
By the way, users cannot claim chunks that have been claimed by other players. This prevents claim stealing. (Intentionally slowing down machinery)

**Comment by P3rf3ctXZer0** [comment]
Error - no because I already removed the mod. All I know is that maybe we need a better way to handle shared claims.

**Comment by TerminatorNL** [comment]
That's actually a very good idea. I will implement it.

**Comment by P3rf3ctXZer0** [comment]
Awesome that will definitely solve some big issues.

**Comment by P3rf3ctXZer0** [comment]
So we are on the same page you can see in the screenshot that I had unclaimed the area is admin and it still didn't actually fix it right?

**Comment by TerminatorNL** [comment]
There's no way for me to know what your configuration settings are at this point.

I am assuming the following so far:
* `I:MAX_CLAIM_RADIUS=50` in config, and was used by person you were trying to help (Defaults to this value if no value specified)
* You were standing on the exact same spot as the person you were trying to help
* You unclaimed a 50 area radius
* Because you only unclaimed a 50 area radius, one chunk further, there's still trackers present. You should have unclaimed 66 (50 + 1 chunk) The spacer was done so people cannot easily claim around you and make your life miserable.

As far as I can tell, it's intended behavior.

When `/acceptoverride` is implemented, this is a non-issue.

**Comment by TerminatorNL** [comment]
I will do some more extensive testing tomorrow as I have to sleep now. But the commit is here, expect a release tomorrow.

**Comment by TerminatorNL** [comment]
Added in [1.12.2-GAMMA-1.5.3](https://github.com/TerminatorNL/Tiquality/releases/tag/1.12.2-GAMMA-1.5.3)
