### ISSUE TITLE
[BUG] Completely Ignoring AcceptOverrides - 1.12.2 -1.5.3-Gamma

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [TerminatorNL/Tiquality#38]
**Describe the bug**

It is ignoring claims still

**To Reproduce**
Steps to reproduce the behavior

Add to modpack server and attempt command

**Which Forge version are you using?**

1.12.2 - 14.23.5.2838

**If you used the word 'error' somewhere, always provide the stack trace along with both _debug.log_ and _latest.log_**

[debug.log](https://github.com/TerminatorNL/Tiquality/files/3365197/debug.log)
[latest.log](https://github.com/TerminatorNL/Tiquality/files/3365198/latest.log)
![2019-07-06 20_29_46-](https://user-images.githubusercontent.com/10351221/60762845-d8a25300-a02d-11e9-8e03-80bf72b97abe.png)

**Comment by TerminatorNL** [comment]
Looks like you used the wrong username (your own!)

You should run the exact command in green...

**Comment by P3rf3ctXZer0** [comment]
... trust me I did nothing wrong both times.

**Comment by P3rf3ctXZer0** [comment]
I use tab to autofill

**Comment by TerminatorNL** [comment]
Please show who's running which command, and show both commands in full.

**Comment by P3rf3ctXZer0** [comment]
I used RetroPrevails as a target and I sent the command. No matter how you ask it I know for a 100% fact I did it correctly. I am Op he is Player.

**Comment by TerminatorNL** [comment]
@P3rf3ctXZer0 
Once again, you're not co-operating here.
Just like #37, this is _an user error_

> Remember too bug reports take time and most people just say "its not working" I gave you all relevant details.

I spent a lot of time making and tweaking Tiquality to get it perfect, *for free*. Fact:
![image](https://user-images.githubusercontent.com/13693773/60806366-11a00c00-a183-11e9-80a4-d9fe212d8ebd.png)
That there, is _programming_ time, and doesn't include any breaks longer than 60 seconds when not typing. If I have 7 hours of actual programming time on a day (generous) I spent 46 full days on writing Tiquality.

**Is it really too much too ask for the precise steps you took?**

"Dude trust me" is **_NOT_** sufficient.

> I gave you all relevant details.
I asked for more details, which you did not supply.

![image](https://user-images.githubusercontent.com/13693773/60806572-a3a81480-a183-11e9-9767-b86e894ca583.png)
As you can clearly see in your screenshot:
You tried to accept a claim override BEFORE you received one from RetroPrevails. (This obviously doesn't work)
Then, you tried to accept your own!

Like I said, at least spend 5 freaking minutes formulating your problem properly, or I won't be able to identify the problem, because as far as I can tell, you're using Tiquality wrong.)

If you're confident enough that you actually did nothing wrong, create a new and properly formulated issue.
